CREATE SCHEMA ORDER_MANAGEMENT;

USE ORDER_MANAGEMENT;

CREATE TABLE VAT_TU
(
    MA_VT  INT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TEN_VT VARCHAR(40) NOT NULL
);

CREATE TABLE PHIEU_XUAT
(
    MA_PX     INT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NGAY_XUAT DATE NOT NULL
);

CREATE TABLE VT_PX
(
    ID    INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MA_VT INT,
    MA_PX INT,
    CONSTRAINT FK_VT_PX FOREIGN KEY (MA_VT) REFERENCES VAT_TU (MA_VT),
    CONSTRAINT FK_PX FOREIGN KEY (MA_PX) REFERENCES PHIEU_XUAT (MA_PX)
);

CREATE TABLE PHIEU_NHAP
(
    MA_PN     INT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NGAY_NHAP DATE NOT NULL
);

CREATE TABLE VT_PN
(
    ID    INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MA_VT INT,
    MA_PN INT,
    CONSTRAINT FK_VT_PN FOREIGN KEY (MA_VT) REFERENCES VAT_TU (MA_VT),
    CONSTRAINT FK_PN FOREIGN KEY (MA_PN) REFERENCES PHIEU_NHAP (MA_PN)
);

CREATE TABLE NHA_CC
(
    MA_NCC  INT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TEN_NCC VARCHAR(40) NOT NULL,
    DIA_CHI TEXT        NOT NULL,
    SDT     VARCHAR(11)
);

CREATE TABLE DON_DH
(
    MA_DH   INT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NGAY_DH DATE NOT NULL,
    MA_NCC  INT,
    CONSTRAINT FK_NCC FOREIGN KEY (MA_NCC) REFERENCES NHA_CC (MA_NCC)
);

CREATE TABLE VT_DDH
(
    ID    INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MA_VT INT,
    MA_DH INT,
    CONSTRAINT FK_VT_DDH FOREIGN KEY (MA_VT) REFERENCES VAT_TU (MA_VT),
    CONSTRAINT FK_DH FOREIGN KEY (MA_DH) REFERENCES DON_DH (MA_DH)
);