CREATE SCHEMA QUAN_LY_BAN_HANG;

USE QUAN_LY_BAN_HANG;

CREATE TABLE CUSTOMERS(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(40) NOT NULL,
    AGE INT(3) NOT NULL
);

CREATE TABLE ORDERS(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CUSTOMNER_ID INT,
    ORDER_DATE DATE,
    TOTAL_PRICE DOUBLE,
    CONSTRAINT FK_CUSTOMER FOREIGN KEY (CUSTOMNER_ID) REFERENCES CUSTOMERS(ID)
);

CREATE TABLE PRODUCT(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(40),
    PRICE DOUBLE
);

CREATE TABLE ORDER_DETAIL(
    ORDER_ID INT,
    PRODUCT_ID INT,
    ORDER_QTY INT,
    PRIMARY KEY (ORDER_ID, PRODUCT_ID),
    CONSTRAINT FK_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID),
    CONSTRAINT FK_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
);